name: Python Package using Conda

on: [push]

jobs:
  backend-application:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.1
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
